config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: :about
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "create successfully"
      redirect_to book_path(@book.id)
    else
      flash.now[:notice] = "create error"
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @post_comment = PostComment.new
  end

  def index
    @books = Book.all
    @user = current_user
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "update successfully"
      redirect_to book_path
    else
      flash.now[:notice] = "update error"
      render :edit
    end
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    user = User.find(book.user_id)
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "update successfully"
      redirect_to user_path
    else
      flash.now[:notice] = "update error"
      render :edit
    end
  end

  def index
    @users = User.all
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
<h1>UserInfo</h1>
<%= image_tag user.get_profile_image(100,100) %>
<h3><%= user.name %></h3>
<p><%= user.introduction %></p>
<div class="my-3">
  <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block' do %>
  <i class="fa-solid fa-user-gear"></i>
  <% end %>
</div>
<h1>New Book</h1>
<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="main row justify-content-center">
  <div class="col-3">
    <h1>Edit Book</h1>
    <%= form_with model: @book do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %><br>
      <%= f.submit 'Update Book', class: 'btn btn-outline-secondary' %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<% if defined?(@book) %>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>
<div class="main row justify-content-center">
  <div class="sidebar col-2">
    <%= render 'sidebar', user: @user %>
  </div>
  <div class="col-5 offset-1">
    <h2>Books</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th>コメント数</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td scope="row"><%= image_tag book.get_image(100,100) %></td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <% if book.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fa-regular fa-heart"></i><%= book.favorites.count %>
              <% end %>
            <td>
            <% end %>
            <td><%= book.post_comments.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/new.html.erb
<div class="main row justify-content-center">
  <div class="col-3">
    <h1>New Book</h1>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のエラーが発生しました
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="main row justify-content-center">
  <div class="sidebar col-2">
    <%= render 'sidebar', user: @user %>
  </div>
  <div class="col-5 offset-1">
    <h1>Book Detail</h1>
    <table class="table">
      <tbody>
        <tr>
          <td scope="row">
            <%= image_tag @book.get_image(100,100) %><br>
            <%= link_to user_path(@user.id) do %>
              <%= @user.name %>
            <% end %>
          </td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if @book.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(@book), method: :delete do %>
                <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(@book), method: :post do %>
                <i class="fa-regular fa-heart"></i><%= @book.favorites.count %>
              <% end %>
            <td>
          <% end %>
          <td>コメント件数：<%= @book.post_comments.count %></td>
          <% if @user == current_user %>
            <td>
              <%= link_to "Edit", edit_book_path(@book), class: 'btn btn-success' %>
            </td>
            <td>
              <%= link_to "Destroy", book_path(@book), method: :delete, class: 'btn btn-danger' %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
    <div class="d-flex">
      <% @book.post_comments.each do |post_comment| %>
        <div>
          <%= image_tag post_comment.user.get_profile_image(100,100) %><br>
          <%= link_to user_path(post_comment.user.id) do %>
            <%= post_comment.user.name %>
          <% end %>
        </div>
        <div class="my-4 ml-3">
          <%= post_comment.comment %>
        </div>
        <% if post_comment.user == current_user %>
          <div class="my-4 ml-3">
            <%= link_to "Destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete, class: 'btn btn-danger' %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div>
      <%= form_with model: [@book, @post_comment] do |f| %>
        <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="text-center block-center">
  <h1>welcome to <i class="fa-solid fa-book"></i><b>Bookers</b> !!</h1>
</div>

app/views/homes/top.html.erb
<div class="text-center block-center">
  <h1>welcome to <i class="fa-solid fa-book"></i><b>Bookers</b> !!</h1>
  <p>
    In <i class="fa-solid fa-book"></i><b>Bookers</b>,<br>
    you can share and exchange your opinions , inpressions , and emotions<br>
    about various books!
  </p>
</div>
<div class="d-flex justify-content-center">
  <div class="col-6">
    <a class="btn btn-primary btn-block" href="/users/sign_in">Log in</a>
    <a class="btn btn-success btn-block" href="/users/sign_up">Sign up</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/68b3f2f467.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <div class="d-flex align-items-center">
                <i class="fa-solid fa-house text-light"></i>
                <%= link_to "Home", user_path(current_user.id), class: 'nav-link text-light' %>
              </div>
            </li>
            <li class="nav-item">
              <div class="d-flex align-items-center">
                <i class="fa-solid fa-users text-light"></i>
                <%= link_to "Users", users_path, class: 'nav-link text-light' %>
              </div>
            </li>
            <li class="nav-item">
              <div class="d-flex align-items-center">
                <i class="fa-solid fa-book-open text-light"></i>
                <%= link_to "Books", books_path, class: 'nav-link text-light' %>
              </div>
            </li>
            <li class="nav-item">
              <div class="d-flex align-items-center">
                <i class="fa-solid fa-right-from-bracket text-light"></i>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
              </div>
            </li>
            <% else %>
            <li class="nav-item">
              <div class="d-flex align-items-center">
                <i class="fa-solid fa-house text-light"></i>
                <%= link_to "Home", root_path, class: 'nav-link text-light' %>
              </div>
            </li>
            <li class="nav-item">
              <div class="d-flex align-items-center">
                <i class="fa-solid fa-link text-light"></i>
                <%= link_to "About", about_path, class: 'nav-link text-light' %>
              </div>
            </li>
            <li class="nav-item">
              <div class="d-flex align-items-center">
                <i class="fa-solid fa-user-plus text-light"></i>
                <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-light' %>
              </div>
            </li>
            <li class="nav-item">
              <div class="d-flex align-items-center">
                <i class="fa-solid fa-right-to-bracket text-light"></i>
                <%= link_to "Log in", new_user_session_path, class: 'nav-link text-light' %>
              </div>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto my-4">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="main row justify-content-center">
  <div class="col-3">
    <h1>User Info</h1>
    <%= form_with model: @user do |f| %>
      <h4>Name</h4>
      <%= f.text_field :name %>
      <h4>Image</h4>
      <%= f.file_field :profile_image, accept: "image/*" %>
      <h4>Introduction</h4>
      <%= f.text_area :introduction %><br>
      <%= f.submit 'Update User', class: 'btn btn-outline-secondary' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="main row justify-content-center">
  <div class="sidebar col-2">
    <%= render 'books/sidebar', user: @user %>
  </div>
  <div class="col-5 offset-1">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td scope="row"><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="main row justify-content-center">
  <div class="sidebar col-2">
    <%= render 'books/sidebar', user: @user %>
  </div>
  <div class="col-5 offset-1">
    <h2>Books</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th>コメント件数：</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td scope="row"><%= image_tag book.get_image(100,100) %></td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td><%= book.post_comments.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>